name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main
    paths:
      - "update.json"

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Purge jsDelivr
        run: |
          curl -L "https://purge.jsdelivr.net/gh/itisthestars/pain-update@main/update.json"
